name: ほとラボ。
url: http://hotolab.net
author: ほと
profile: ゆとりWebエンジニア
paginate: 10
markdown: redcarpet
highlighter: pygments
permalink: blog/:title
safe: true
lsi: false
redcarpet:
  extensions: [tables]
exclude: [Rakefile]
